### PR TITLE
Use only source files relevant to homekit

### PR DESCRIPTION
**Pull request by HomeACcessoryKid**
reduces flash footprint by 8672 bytes. RAM usage is the same.

### CODE REVIEW

**Comment by maximkulkin** [comment]
Well, it is kind of wrong to do it here as this component just packages wolfssl lib for esp-open-rtos regardless of where it will be used. But what is more interesting: does this actually decrease binary size? Do you have aumbers?

**Comment by HomeACcessoryKid** [comment]
The numbers are part of the comment of initial commit

**Comment by maximkulkin** [comment]
Well, to get 8K reduction all you need to do is to disable MD5 and SHA (I got 8K reduction on my setup just by specifying NO_MD5 and NO_SHA). No need to manually list source files. Thus, it looks like compiler already does a good job of eliminating dead code.

So, I think that it would be better to leavethis component to be generic and just enable MD5/SHA flags in homekit component.

**Comment by HomeACcessoryKid** [comment]
fair point, I hadn't tested that!
I'm withdrawing this PR

**Pull request closed without merging**
